all:	sa.timer kernel

sa.timer:
	cd standalone ; make all
instsa:
	cd standalone ; make install
	
kernel:
	cd kernel ; make all

instkern:
	cd kernel ; make install
	
clean:	
	cd standalone ; make clean
	cd kernel ; make clean
