typedef	struct { int r[1]; } *	physadr;
typedef	unsigned long	daddr_t;
typedef	char *		caddr_t;
typedef	unsigned int	uint;
typedef	unsigned short	ushort;
typedef	ushort		ino_t;
typedef char		cnt_t;
typedef	long		time_t;
typedef	int		label_t[10];
typedef	short		dev_t;
typedef	long		off_t;
typedef	long		paddr_t;
typedef	long		saddr_t;
typedef	long		uaddr_t;
typedef	long		key_t;
