/"relid     "12cn
.+12/"relowner  "2cn
.+2/"relspec   "bn
.+1/"relindxd  "bn
.+1/"relstat   "on
.+2/"relsave   "Yn
.+4/"reltups   "Dn
.+4/"relatts   "dn
.+2/"relwid    "dn
.+2/"relprim   "Dn
.+4/"relspare  "Dn
.+4/"relfp     "dn
.+2/"relopn    "dn
.+2/"reltid    "Dn
.+4/"reladds   "Dn
.+4/"reloff  "7d
.+100/"relfrmt "7b
.+50/"relfrml "7b
.+50/"relxtra "7b
.+50/"relgivn "7b
