clean:
	cd conf ; make $@
	cd dev ; make $@
	cd sys ; make $@

all:
	cd conf ; make $@
	cd dev ; make $@
	cd sys ; make $@

install: all
	cd conf ; make $@
	cd dev ; make $@
	cd sys ; make $@
	cd h ; make $@