AS=	as
ASFLAGS=
OBJ=	access.o acct.o alarm.o brk.o chdir.o chmod.o chown.o close.o creat.o \
	dup.o execl.o execle.o execv.o execve.o exit.o fcntl.o fork.o fstat.o \
	getegid.o geteuid.o getgid.o getpid.o getppid.o getuid.o ioctl.o \
	kill.o link.o lseek.o mknod.o mount.o nice.o open.o pause.o pipe.o \
	profil.o ptrace.o read.o setgid.o setpgrp.o setuid.o signal.o stat.o \
	stime.o sync.o time.o times.o ulimit.o umask.o umount.o uname.o \
	unlink.o ustat.o utime.o wait.o write.o

all: $(OBJ)

clean:
	rm -f $(OBJ)
